services:
  todoop_frontend:
    build: .
    ports:
      - 5173:5173
    env_file:
        - .env
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    command: npm run dev

volumes:
  node_modules: